---
rustify_deploy_path: "/srv/rustify"
rustify_env: {}
restic_version: 0.16.0

rustify_censor_blacklist: []
rustify_censor_whitelist: []

rustify_docker_registry: false
rustify_docker_registry_url: "https://index.docker.io/v1/"
rustify_docker_registry_username: ""
rustify_docker_registry_password: ""

rustify_db_password:
rustify_db_username:
rustify_db_database:
rustify_db_port: 5432
rustify_db_host: db
rustify_docker_network: rustify

rustify_alloy_grafana_cloud_url: ""
rustify_alloy_grafana_cloud_username: ""
rustify_alloy_grafana_cloud_api_key: ""
rustify_pushgateway_instance: "prod"

rustify_letsencrypt_email:
rustify_hurricane_tokens:
rustify_domain_name:
rustify_port: 443
