# https://rust-lang.github.io/rustup-components-history/
[toolchain]
channel = "nightly-2025-11-02"
targets = ["x86_64-unknown-linux-gnu"]
components = ["rust-analyzer", "clippy", "rustfmt"]
profile = "minimal"
